version: '3.8'
services:
  webapp:
    build: .
    environment:
      POSTGRES_URL: jdbc:postgresql://database:5432/time-trials
      POSTGRES_USER: hrusch
      POSTGRES_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - "database"

  database:
    image: postgres
    environment:
      POSTGRES_USER: hrusch
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: time-trials
    volumes:
      - time-trials-volume:/var/lib/postgresql/data

volumes:
  time-trials-volume:
